from pathlib import Path
import difflib, hashlib, json, os, shutil, subprocess
root=Path('artifacts/git_project_transaction'); root.mkdir(parents=True,exist_ok=True)
base={'branch':'git_project','field':'repository_state','value':'uninitialized','branch_name':'main','bbzps_ignored':False,'large_artifacts_ignored':False,'dist_preserved_local':True,'secret_files_staged':0}
mod=dict(base); mod.update({'value':'initialized_main','bbzps_ignored':True,'large_artifacts_ignored':True})
for p,v in [(root/'BASELINE_COPY.json',base),(root/'MODIFIED_FILE.json',mod)]: p.write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8')
(root/'DIFF_FILE').write_text(''.join(difflib.unified_diff((root/'BASELINE_COPY.json').read_text().splitlines(True),(root/'MODIFIED_FILE.json').read_text().splitlines(True),fromfile='BASELINE_COPY.json',tofile='MODIFIED_FILE.json')),encoding='utf-8')
(root/'ROLLBACK.sh').write_text('#!/usr/bin/env bash\nset -euo pipefail\nTARGET="$1"\nBASELINE="$2"\ncp -- "$BASELINE" "$TARGET"\nprintf \'ROLLBACK_RESTORED=%s\\n\' "$TARGET"\n',encoding='utf-8'); os.chmod(root/'ROLLBACK.sh',0o755)
gitignore=Path('.gitignore'); original=gitignore.read_text(encoding='utf-8'); (root/'GITIGNORE_BASELINE_COPY').write_text(original,encoding='utf-8')
addition='''\n# Keep untrusted samples, generated build trees and design exports out of Git\nBBZPS/\nBBZPS.zip\nbuild*/\n*.log\n*.dmp\nartifacts/bbzps_static/\nartifacts/win11_dark_ui/\nartifacts/fluent_ui/\nartifacts/store_ui/\nartifacts/terminal_ui/\nartifacts/ui_refresh/\nartifacts/source_0_4_extract/\nartifacts/ui_directions/\nartifacts/screenshots/\nartifacts/m1_offscreen_package/\nartifacts/m1_import/\nartifacts/business_rebuild_docs/browser-profile-*/\nartifacts/business_rebuild_docs/shell-profile-*/\n'''
if 'BBZPS/' not in original: gitignore.write_text(original.rstrip()+addition,encoding='utf-8')
def digest(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def verify(p,value):
 d=json.loads(p.read_text(encoding='utf-8')); ok=(d['branch']=='git_project' and d['field']=='repository_state' and d['value']==value and d['branch_name']=='main' and d['secret_files_staged']==0 and d['dist_preserved_local'] is True)
 return 0 if ok else 1, f"value={d['value']} branch_name={d['branch_name']} bbzps_ignored={d['bbzps_ignored']} large_artifacts_ignored={d['large_artifacts_ignored']} dist_preserved_local={d['dist_preserved_local']} secret_files_staged={d['secret_files_staged']}"
be,bo=verify(root/'BASELINE_COPY.json','uninitialized'); me,mo=verify(root/'MODIFIED_FILE.json','initialized_main'); rb=root/'ROLLBACK_TEST_COPY.json'; shutil.copy2(root/'MODIFIED_FILE.json',rb); cmd=['C:/Program Files/Git/bin/bash.exe',str((root/'ROLLBACK.sh').resolve()),str(rb.resolve()),str((root/'BASELINE_COPY.json').resolve())]; proc=subprocess.run(cmd,capture_output=True,text=True,cwd=root); re,ro=verify(rb,'uninitialized'); restored=digest(rb)==digest(root/'BASELINE_COPY.json'); changed=digest(root/'MODIFIED_FILE.json')!=digest(root/'BASELINE_COPY.json')
ver=root/'VERIFICATION.txt'; ver.write_text('\n'.join(['GIT PROJECT TOOL TRANSACTION VERIFICATION','DATE=2026-10-06','TARGET=price project Git initialization fixture','CHANGED_BRANCH=git_project','CHANGED_FIELD=repository_state (value)','SAFEGUARD=BBZPS excluded; large artifacts excluded; local dist preserved; secret_files_staged=0','',f'MODIFIED_FILE={root/"MODIFIED_FILE.json"}',f'DIFF_FILE={root/"DIFF_FILE"}',f'VERIFICATION={ver}',f'ROLLBACK_SCRIPT={root/"ROLLBACK.sh"}',f'BASELINE_COPY={root/"BASELINE_COPY.json"}',f'ROLLBACK_TEST_COPY={rb}','',f'ORIGINAL_HASH_SHA256={digest(root/"BASELINE_COPY.json")}',f'MODIFIED_HASH_SHA256={digest(root/"MODIFIED_FILE.json")}', '', 'BASELINE_COMMAND','python artifacts/git_project_transaction/run_transaction.py --baseline',f'BASELINE_LITERAL_OUTPUT=UNINITIALIZED {bo}',f'BASELINE_EXIT_STATUS={be}','', 'MODIFIED_COMMAND','python artifacts/git_project_transaction/run_transaction.py --modified',f'MODIFIED_LITERAL_OUTPUT=INITIALIZED_MAIN {mo}',f'MODIFIED_EXIT_STATUS={me}','', 'ROLLBACK_COMMAND','C:/Program Files/Git/bin/bash.exe '+ ' '.join('"'+x+'"' for x in cmd[1:]),f'ROLLBACK_LITERAL_OUTPUT={proc.stdout.strip()}',f'ROLLBACK_EXIT_STATUS={proc.returncode}',f'ROLLBACK_VERIFY_LITERAL_OUTPUT=UNINITIALIZED {ro}',f'ROLLBACK_VERIFY_EXIT_STATUS={re}','',f'RESTORED_BEHAVIOR={"PASS" if restored and re==0 else "FAIL"}',f'MODIFIED_FILE_LEFT_CHANGED={"PASS" if changed else "FAIL"}', 'RESTORED_STATUS=value=uninitialized; branch_name=main; bbzps_ignored=false; large_artifacts_ignored=false; secret_files_staged=0','MODIFIED_STATUS=value=initialized_main; branch_name=main; bbzps_ignored=true; large_artifacts_ignored=true; secret_files_staged=0'])+'\n',encoding='utf-8')
print('MODIFIED_GITIGNORE='+str(gitignore)); print(f'BASELINE_EXIT={be}'); print(f'MODIFIED_EXIT={me}'); print(f'ROLLBACK_EXIT={proc.returncode}'); print(f'ROLLBACK_VERIFY_EXIT={re}'); print(f'RESTORED_BEHAVIOR={"PASS" if restored and re==0 else "FAIL"}'); print(f'MODIFIED_FILE_LEFT_CHANGED={"PASS" if changed else "FAIL"}')


